import { Database } from "../../backend/src/db/client";
import { Config } from "../../backend/src/config";

const SQL_STMTS = [
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[payroll_history_header]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[payroll_history_header] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [history_id] [varchar](50) NOT NULL,
    [period_month] [int] NOT NULL,
    [period_year] [int] NOT NULL,
    [division_code] [varchar](10) NULL,
    [gang_code] [varchar](20) NULL,
    [gang_description] [varchar](100) NULL,
    [total_employees] [int] NULL,
    [total_hk] [decimal](10, 2) NULL,
    [total_hari_kerja] [int] NULL,
    [total_cuti_tahunan] [int] NULL,
    [total_cuti_sakit] [int] NULL,
    [total_cuti_minggu] [int] NULL,
    [total_cuti_nasional] [int] NULL,
    [total_upah_dasar] [decimal](18, 4) NULL,
    [total_upah_pokok] [decimal](18, 4) NULL,
    [total_gaji_pokok] [decimal](18, 4) NULL,
    [total_beras] [decimal](18, 4) NULL,
    [total_jabatan] [decimal](18, 4) NULL,
    [total_masa_kerja] [decimal](18, 4) NULL,
    [total_lembur] [decimal](18, 4) NULL,
    [total_tunjangan] [decimal](18, 4) NULL,
    [total_premi_brondol] [decimal](18, 4) NULL,
    [total_premi_prunning] [decimal](18, 4) NULL,
    [total_premi_insentif] [decimal](18, 4) NULL,
    [total_premi_kinerja] [decimal](18, 4) NULL,
    [total_premi] [decimal](18, 4) NULL,
    [dynamic_premi_data] [nvarchar](max) NULL,
    [total_koreksi] [decimal](18, 4) NULL,
    [total_potongan] [decimal](18, 4) NULL,
    [total_pph21] [decimal](18, 4) NULL,
    [total_bpjs_pekerja] [decimal](18, 4) NULL,
    [total_bpjs_majikan] [decimal](18, 4) NULL,
    [total_spsi] [decimal](18, 4) NULL,
    [dynamic_potongan_data] [nvarchar](max) NULL,
    [total_upah_kotor] [decimal](18, 4) NULL,
    [total_upah_bersih] [decimal](18, 4) NULL,
    [total_ffb_weight] [decimal](10, 2) NULL,
    [total_weight_tbs] [decimal](10, 2) NULL,
    [informasi_tambahan] [nvarchar](max) NULL,
    [created_by] [varchar](50) NULL,
    [source_endpoint] [varchar](100) NULL,
    [is_locked] [bit] NULL,
    [lock_reason] [varchar](200) NULL,
    [created_at] [datetime] DEFAULT GETDATE(),
    CONSTRAINT [PK_payroll_history_header] PRIMARY KEY CLUSTERED ([id] ASC)
)
END`,
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[payroll_history_detail]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[payroll_history_detail] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [history_id] [varchar](50) NOT NULL,
    [master_id] [int] NOT NULL,
    [emp_code] [varchar](20) NOT NULL,
    [emp_name] [varchar](100) NULL,
    [nik] [varchar](50) NULL,
    [gender] [varchar](10) NULL,
    [gang_code] [varchar](20) NULL,
    [division_code] [varchar](10) NULL,
    [loc_code] [varchar](20) NULL,
    [status_ptkp] [varchar](20) NULL,
    [kategori_ter] [varchar](10) NULL,
    [hari_kerja] [int] NULL,
    [cuti_tahunan_hari] [int] NULL,
    [cuti_sakit_haid_hari] [int] NULL,
    [cuti_minggu_hari] [int] NULL,
    [cuti_nasional_hari] [int] NULL,
    [jumlah_hk] [decimal](10, 2) NULL,
    [total_jam_kerja] [decimal](10, 2) NULL,
    [upah_dasar] [decimal](18, 4) NULL,
    [upah_pokok] [decimal](18, 4) NULL,
    [gaji_pokok] [decimal](18, 4) NULL,
    [gaji_pokok_ideal] [decimal](18, 4) NULL,
    [gaji_pokok_aktual] [decimal](18, 4) NULL,
    [koreksi_hk] [decimal](10, 2) NULL,
    [beras_rate] [decimal](18, 4) NULL,
    [beras_jumlah] [decimal](18, 4) NULL,
    [jabatan_rate] [decimal](18, 4) NULL,
    [jabatan_jumlah] [decimal](18, 4) NULL,
    [masa_kerja_tahun] [int] NULL,
    [masa_kerja_rate] [decimal](18, 4) NULL,
    [masa_kerja_jumlah] [decimal](18, 4) NULL,
    [lembur_jam] [decimal](10, 2) NULL,
    [lembur_rate] [decimal](18, 4) NULL,
    [lembur_jumlah] [decimal](18, 4) NULL,
    [lembur_records] [nvarchar](max) NULL,
    [total_tunjangan] [decimal](18, 4) NULL,
    [premi_brondol] [decimal](18, 4) NULL,
    [premi_pph] [decimal](18, 4) NULL,
    [total_premi] [decimal](18, 4) NULL,
    [premi_detail] [nvarchar](max) NULL,
    [pot_spsi] [decimal](18, 4) NULL,
    [pot_pph21] [decimal](18, 4) NULL,
    [pot_koreksi] [decimal](18, 4) NULL,
    [pot_bpjs_kesehatan_pekerja] [decimal](18, 4) NULL,
    [pot_bpjs_kesehatan_majikan] [decimal](18, 4) NULL,
    [pot_bpjs_pensiun_pekerja] [decimal](18, 4) NULL,
    [pot_bpjs_pensiun_majikan] [decimal](18, 4) NULL,
    [pot_bpjs_pekerja_total] [decimal](18, 4) NULL,
    [pot_astek_pekerja] [decimal](18, 4) NULL,
    [pot_astek_majikan] [decimal](18, 4) NULL,
    [pot_astek_jumlah] [decimal](18, 4) NULL,
    [potongan_detail] [nvarchar](max) NULL,
    [total_potongan] [decimal](18, 4) NULL,
    [total_potongan_bersih] [decimal](18, 4) NULL,
    [jumlah_upah_kotor] [decimal](18, 4) NULL,
    [upah_kotor_pajak] [decimal](18, 4) NULL,
    [penghasilan_bruto] [decimal](18, 4) NULL,
    [tarif_pajak_ter] [decimal](5, 2) NULL,
    [pph21_ter] [decimal](18, 4) NULL,
    [upah_bersih] [decimal](18, 4) NULL,
    [task_code] [varchar](50) NULL,
    [task_desc] [varchar](100) NULL,
    [shortage_details] [nvarchar](max) NULL,
    [shortage_total_hours] [decimal](10, 2) NULL,
    CONSTRAINT [PK_payroll_history_detail] PRIMARY KEY CLUSTERED ([id] ASC)
)
END`,
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[history_taskreg]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[history_taskreg] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [history_id] [varchar](50) NOT NULL,
    [original_master_id] [int] NULL,
    [reg_no] [varchar](50) NULL,
    [reg_date] [datetime] NULL,
    [emp_code] [varchar](20) NULL,
    [gang_code] [varchar](20) NULL,
    [division_code] [varchar](10) NULL,
    [original_line_id] [int] NULL,
    [line_no] [int] NULL,
    [trx_date] [datetime] NULL,
    [task_code] [varchar](50) NULL,
    [task_desc] [varchar](100) NULL,
    [hours] [decimal](10, 2) NULL,
    [ot] [bit] NULL,
    [rate] [decimal](18, 4) NULL,
    [amount] [decimal](18, 4) NULL,
    [tapping_type] [varchar](20) NULL,
    [location_code] [varchar](20) NULL,
    [status] [varchar](20) NULL,
    [is_cuti_tahunan] [bit] NULL,
    [is_cuti_sakit] [bit] NULL,
    [is_cuti_minggu] [bit] NULL,
    [is_cuti_nasional] [bit] NULL,
    [is_hari_kerja] [bit] NULL,
    [is_lembur] [bit] NULL,
    [period_month] [int] NOT NULL,
    [period_year] [int] NOT NULL,
    [source_table] [varchar](50) NOT NULL,
    [created_at] [datetime] DEFAULT GETDATE(),
    CONSTRAINT [PK_history_taskreg] PRIMARY KEY CLUSTERED ([id] ASC)
)
END`,
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[history_adtrans]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[history_adtrans] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [history_id] [varchar](50) NOT NULL,
    [original_master_id] [int] NULL,
    [doc_no] [varchar](50) NULL,
    [doc_date] [datetime] NULL,
    [doc_desc] [varchar](100) NULL,
    [emp_code] [varchar](20) NULL,
    [gang_code] [varchar](20) NULL,
    [division_code] [varchar](10) NULL,
    [original_line_id] [int] NULL,
    [line_no] [int] NULL,
    [task_code] [varchar](50) NULL,
    [task_desc] [varchar](100) NULL,
    [amount] [decimal](18, 4) NULL,
    [quantity] [decimal](18, 4) NULL,
    [uom] [varchar](20) NULL,
    [category] [varchar](50) NULL,
    [sub_category] [varchar](50) NULL,
    [is_dynamic] [bit] NULL,
    [dynamic_header_name] [varchar](50) NULL,
    [is_premi_pph] [bit] NULL,
    [is_koreksi] [bit] NULL,
    [is_potongan] [bit] NULL,
    [is_premi] [bit] NULL,
    [period_month] [int] NOT NULL,
    [period_year] [int] NOT NULL,
    [source_table] [varchar](50) NOT NULL,
    [created_at] [datetime] DEFAULT GETDATE(),
    CONSTRAINT [PK_history_adtrans] PRIMARY KEY CLUSTERED ([id] ASC)
)
END`,
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[history_gang_member]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[history_gang_member] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [history_id] [varchar](50) NOT NULL,
    [gang_code] [varchar](20) NOT NULL,
    [gang_description] [varchar](100) NULL,
    [division_code] [varchar](10) NOT NULL,
    [loc_code] [varchar](20) NULL,
    [emp_code] [varchar](20) NOT NULL,
    [emp_name] [varchar](100) NULL,
    [join_date] [datetime] NULL,
    [is_active] [bit] NULL,
    [period_month] [int] NOT NULL,
    [period_year] [int] NOT NULL,
    [source_table] [varchar](50) NOT NULL,
    [created_at] [datetime] DEFAULT GETDATE(),
    CONSTRAINT [PK_history_gang_member] PRIMARY KEY CLUSTERED ([id] ASC)
)
END`,
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[history_metadata]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[history_metadata] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [history_id] [varchar](50) NOT NULL,
    [operation] [varchar](20) NOT NULL,
    [entity_type] [varchar](50) NOT NULL,
    [entity_id] [varchar](50) NULL,
    [period_month] [int] NOT NULL,
    [period_year] [int] NOT NULL,
    [division_code] [varchar](10) NULL,
    [gang_code] [varchar](20) NULL,
    [description] [varchar](255) NULL,
    [old_values] [nvarchar](max) NULL,
    [new_values] [nvarchar](max) NULL,
    [record_count] [int] NULL,
    [status] [varchar](20) NULL,
    [error_message] [varchar](max) NULL,
    [performed_by] [varchar](50) NULL,
    [ip_address] [varchar](50) NULL,
    [user_agent] [varchar](255) NULL,
    [session_id] [varchar](50) NULL,
    [performed_at] [datetime] DEFAULT GETDATE(),
    CONSTRAINT [PK_history_metadata] PRIMARY KEY CLUSTERED ([id] ASC)
)
END`,
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[history_hr_employee]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[history_hr_employee] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [history_id] [varchar](50) NOT NULL,
    [period_month] [int] NOT NULL,
    [period_year] [int] NOT NULL,
    [nik] [varchar](50) NULL,
    [emp_code] [varchar](20) NOT NULL,
    [emp_name] [varchar](100) NULL,
    [company_code] [varchar](10) NULL,
    [division_code] [varchar](10) NULL,
    [loc_code] [varchar](20) NULL,
    [gang_code] [varchar](20) NULL,
    [job_code] [varchar](20) NULL,
    [position] [varchar](100) NULL,
    [join_date] [datetime] NULL,
    [terminate_date] [datetime] NULL,
    [status] [varchar](20) NULL,
    [employee_type] [varchar](20) NULL,
    [gender] [varchar](10) NULL,
    [religion] [varchar](20) NULL,
    [birth_place] [varchar](50) NULL,
    [birth_date] [datetime] NULL,
    [marital_status] [varchar](20) NULL,
    [tax_status] [varchar](20) NULL,
    [ptkp_beras] [varchar](20) NULL,
    [ptkp_pajak] [varchar](20) NULL,
    [upah_dasar] [decimal](18, 4) NULL,
    [total_hk] [decimal](10, 2) NULL,
    [source_table] [varchar](50) NOT NULL,
    [created_at] [datetime] DEFAULT GETDATE(),
    CONSTRAINT [PK_history_hr_employee] PRIMARY KEY CLUSTERED ([id] ASC)
)
END`,
    `IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[history_hr_gang]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[history_hr_gang] (
    [id] [int] IDENTITY(1,1) NOT NULL,
    [history_id] [varchar](50) NOT NULL,
    [period_month] [int] NOT NULL,
    [period_year] [int] NOT NULL,
    [division_code] [varchar](10) NULL,
    [loc_code] [varchar](20) NULL,
    [gang_code] [varchar](20) NOT NULL,
    [gang_description] [varchar](100) NULL,
    [mandor_code] [varchar](20) NULL,
    [mandor_name] [varchar](100) NULL,
    [mandor_1_code] [varchar](20) NULL,
    [mandor_1_name] [varchar](100) NULL,
    [assistant_code] [varchar](20) NULL,
    [assistant_name] [varchar](100) NULL,
    [total_members] [int] NULL,
    [is_active] [bit] NULL,
    [source_table] [varchar](50) NOT NULL,
    [created_at] [datetime] DEFAULT GETDATE(),
    CONSTRAINT [PK_history_hr_gang] PRIMARY KEY CLUSTERED ([id] ASC)
)
END`
];

async function run() {
    const extendDb = Database.getInstance(Config.DB_EXTEND_DATABASE, Config.DB_EXTEND_PROFILE);
    console.log("Creating tables on ", Config.DB_EXTEND_DATABASE);
    for (const sql of SQL_STMTS) {
        try {
            await extendDb.query(sql);
            console.log("Table created successfully");
        } catch (e: any) {
            console.error("Error creating table:", e.message);
        }
    }
}
run();
